In [37]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [38]:
dataset = pd.read_csv("medical_insurance.csv")
print(dataset)

      age     sex  bmi  children smoker     region  charges
0      19  female   27         0    yes  southwest    16884
1      18    male   33         1     no  southeast     1725
2      28    male   33         3     no  southeast     4449
3      33    male   22         0     no  northwest    13316
4      32    male   28         0     no  northwest     3866
...   ...     ...  ...       ...    ...        ...      ...
2767   47  female   45         1     no  southeast     8569
2768   21  female   34         0     no  southwest     2020
2769   19    male   26         1    yes  northwest    16450
2770   23    male   18         0     no  northwest    21595
2771   54    male   31         0     no  southwest     9850

[2772 rows x 7 columns]

In [39]:
dataset.head()

   age     sex  bmi  children smoker     region  charges
0   19  female   27         0    yes  southwest    16884
1   18    male   33         1     no  southeast     1725
2   28    male   33         3     no  southeast     4449
3   33    male   22         0     no  northwest    13316
4   32    male   28         0     no  northwest     3866

In [40]:
dataset.tail()

      age     sex  bmi  children smoker     region  charges
2767   47  female   45         1     no  southeast     8569
2768   21  female   34         0     no  southwest     2020
2769   19    male   26         1    yes  northwest    16450
2770   23    male   18         0     no  northwest    21595
2771   54    male   31         0     no  southwest     9850

In [41]:
print('rows: ', dataset.shape[0])
print('columns: ', dataset.shape[1])

rows:  2772
columns:  7

In [42]:
dataset.isnull()

        age    sex    bmi  children  smoker  region  charges
0     False  False  False     False   False   False    False
1     False  False  False     False   False   False    False
2     False  False  False     False   False   False    False
3     False  False  False     False   False   False    False
4     False  False  False     False   False   False    False
...     ...    ...    ...       ...     ...     ...      ...
2767  False  False  False     False   False   False    False
2768  False  False  False     False   False   False    False
2769  False  False  False     False   False   False    False
2770  False  False  False     False   False   False    False
2771  False  False  False     False   False   False    False

[2772 rows x 7 columns]

In [43]:
dataset.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [44]:
dataset.dtypes

age         int64
sex           str
bmi         int64
children    int64
smoker        str
region        str
charges     int64
dtype: object

In [45]:
print(dataset.columns)
for i in dataset.columns:
    print(i)

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='str')
age
sex
bmi
children
smoker
region
charges

In [46]:
dataset.count()

age         2772
sex         2772
bmi         2772
children    2772
smoker      2772
region      2772
charges     2772
dtype: int64

In [47]:
dataset.describe()

               age          bmi     children       charges
count  2772.000000  2772.000000  2772.000000   2772.000000
mean     39.109668    30.202381     1.086219  13315.885281
std      14.081459     6.045642     1.123611  11993.749218
min      18.000000    15.000000     0.000000   1121.000000
25%      26.000000    26.000000     0.000000   4827.000000
50%      39.000000    30.000000     1.000000   9715.000000
75%      51.000000    34.000000     2.000000  15888.250000
max      64.000000    53.000000     5.000000  63770.000000

In [48]:
#Data Pre-Processing
dataset.shape

(2772, 7)

In [49]:
dataset.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [50]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 2772 entries, 0 to 2771
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       2772 non-null   int64
 1   sex       2772 non-null   str
 2   bmi       2772 non-null   int64
 3   children  2772 non-null   int64
 4   smoker    2772 non-null   str
 5   region    2772 non-null   str
 6   charges   2772 non-null   int64
dtypes: int64(4), str(3)
memory usage: 195.5 KB

In [51]:
dataset['bmi'] = dataset['bmi'].fillna(dataset['bmi'].mean())

In [52]:
dataset.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [53]:
def fillnaMean(col):
    for i in col:
        dataset[i] = dataset[i].fillna(dataset[i].mean())

columns = ['bmi', 'children', 'charges']
fillnaMean(columns)

In [54]:
dataset['children'] = dataset['children'].astype(int) 
dataset['charges'] = dataset['charges'].astype(int) 
dataset['bmi'] = dataset['bmi'].astype(int)

In [55]:
dataset.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [56]:
dataset.to_csv('medical_insurance.csv', index=False, header=True)

In [57]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 2772 entries, 0 to 2771
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       2772 non-null   int64
 1   sex       2772 non-null   str
 2   bmi       2772 non-null   int64
 3   children  2772 non-null   int64
 4   smoker    2772 non-null   str
 5   region    2772 non-null   str
 6   charges   2772 non-null   int64
dtypes: int64(4), str(3)
memory usage: 195.5 KB